In [1]:
# load a coffea file
from coffea.util import load
import os
import awkward as ak
import numpy as np
import matplotlib.pyplot as plt
import mplhep as hep
import matplotlib
matplotlib.rcParams["figure.dpi"] = 300


In [16]:
input = "/work/mmalucch/out_hh4b/out_vbf_jets_test/output_all.coffea"

o = load(f"{input}")

In [17]:
sample=list(o["columns"].keys())[0]
dataset=list(o["columns"][sample].keys())[0]
category=list(o["columns"][sample][dataset].keys())[0]
print(o["columns"][sample][dataset].keys())
col=o["columns"][sample][dataset][category]
for k in col.keys():
    print(k)
    col[k]=col[k].value#[col[k].value!=-999]


dict_keys(['4b_region'])
weight
events_etaProduct
events_deltaEta_matched
events_jj_mass_matched
events_nJetVBF_matched
Jet_N
Jet_index
Jet_pt
Jet_btagPNetQvG
Jet_eta
Jet_btagPNetB
Jet_phi
Jet_mass
JetVBFNotFromHiggs_N
JetVBFNotFromHiggs_index
JetVBFNotFromHiggs_pt
JetVBFNotFromHiggs_btagPNetQvG
JetVBFNotFromHiggs_eta
JetVBFNotFromHiggs_btagPNetB
JetVBFNotFromHiggs_phi
JetVBFNotFromHiggs_mass
JetGoodFromHiggsOrdered_index
JetGoodFromHiggsOrdered_pt
JetGoodFromHiggsOrdered_btagPNetQvG
JetGoodFromHiggsOrdered_eta
JetGoodFromHiggsOrdered_btagPNetB
JetGoodFromHiggsOrdered_phi
JetGoodFromHiggsOrdered_mass
JetVBF_matching_N
JetVBF_matching_index
JetVBF_matching_pt
JetVBF_matching_btagPNetQvG
JetVBF_matching_eta
JetVBF_matching_btagPNetB
JetVBF_matching_phi
JetVBF_matching_mass
JetVBF_matched_N
JetVBF_matched_index
JetVBF_matched_pt
JetVBF_matched_btagPNetQvG
JetVBF_matched_eta
JetVBF_matched_btagPNetB
JetVBF_matched_phi
JetVBF_matched_mass
JetVBF_generalSelection_matched_N
JetVBF_generalSele

In [18]:
print(len(col["JetGoodFromHiggsOrdered_pt"]))
print(len(col["weight"]))
print(len(col["HH_pt"]))
print(len(col["quarkVBF_generalSelection_matched_pt"]))
print(len(col["quarkVBF_pt"]))
print(len(col["JetVBFLeadingMjjNotFromHiggs_pt"]))

7455
7455
7455
12690
14910
14910


In [21]:
print((col["JetGoodFromHiggsOrdered_pt"]))
print(col["JetVBFLeadingMjjNotFromHiggs_pt"][col["JetVBFLeadingMjjNotFromHiggs_pt"]<12])
print(col["JetVBFLeadingMjjNotFromHiggs_eta"][abs(col["JetVBFLeadingMjjNotFromHiggs_eta"])>4.6])


[[147.86612   70.64549   87.6789    83.01369 ]
 [ 71.70511   54.774662  79.50374   54.04211 ]
 [ 86.90677   41.731636  39.493473  34.71512 ]
 ...
 [124.24467   47.973507  62.656864  46.424488]
 [112.98882   54.874634  38.329338  35.514175]
 [169.96036   56.48333   62.93993   42.742615]]
[11.737123 11.826293 11.565462 11.300092]
[-4.6191406 -4.676758  -4.665039  -4.6054688 -4.6845703  4.6640625
 -4.6054688  4.6210938 -4.6103516 -4.602539   4.682617  -4.6708984
  4.6103516  4.6035156 -4.6347656  4.616211  -4.6728516  4.6679688
 -4.623047  -4.682617  -4.6152344  4.600586   4.698242  -4.6728516
 -4.694336   4.698242   4.685547   4.6953125  4.6210938  4.6679688
  4.616211   4.604492   4.604492   4.658203  -4.6757812  4.6347656
  4.6728516  4.666992   4.618164  -4.6728516  4.614258   4.6210938
  4.6464844  4.640625  -4.6191406 -4.600586   4.6416016 -4.6240234
 -4.626953   4.6640625 -4.6054688 -4.6992188 -4.6152344 -4.671875
 -4.6601562 -4.6660156 -4.6777344  4.6416016  4.600586   4.635742
 -